[package]
name = "stack-based-nightmare"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sbn"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
color-eyre = "0.6"
